# Generated by Django 5.2.4 on 2025-08-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller')], default='Customer', max_length=20),
        ),
    ]
