# Generated by Django 5.2.4 on 2025-11-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_sellerprofile_user_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
