# Generated by Django 5.2.4 on 2025-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_customer_name_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
