# Generated by Django 5.2.4 on 2025-11-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
